### PR TITLE
Benchmarking across backends

### PR DESCRIPTION
**Pull request by atait**
Small changes to the benchmarking scripts, most notably a batch script to launch across different backends. The scripts take a new optional argument of save file name so the results can be easily recovered for plotting.

### CODE REVIEW

**Comment by hunse** [comment]
Thanks for this Alex!

The fact that you're actively using these benchmarks encouraged me to bite the bullet and actually revise them so they're easier to use from the command line, and make it easier to add different backends or backend options to profile.

In "Add SimRunner for loading backends in benchmarks" I add the `SimRunner` and child classes so we don't have as much special-case code for different simulators/backends. Now, to add another backend, or e.g. this backend with different options, it should be as easy as adding a line to the bottom of `nengo_ocl.utils` that adds to the `SimRunner` class. I haven't tested this with #188 yet, so it's possible there'll be a few changes once I integrate with that, but I think that this system should work well. I did consider allowing the user to have some sort of benchmark config file, which could allow custom backends/simulators to be added to `SimRunner` without needing to modify `nengo_ocl.utils`. However, that seemed like overkill for the moment.

In "Use click for benchmarks", I redo the the CLI for all the benchmark scripts so that it's easy to specify all the options, and we don't have to use the hacky `argv` stuff anymore. I also redo `benchmark_backends.py` to use `subprocess` rather than `exec`.

Let me know what you think. As I said, there may be more changes once I integrate with #188, but I expect those to be minor.

**Comment by atait** [comment]
I like the changes you put. Ideally, these would be flexible enough to evaluate new features, demonstrate performance, and be easy for first-time users (The directory is called examples after all). I think click is helping with that. My other use case is comparing within *GPU* backends: laptop (Iris), lab computer (GeForce), and cluster (Tesla). It's much easier if you can do it with a bash script rather than rsync-ing a python file, although the latter does work.

As far as `SimRunner`, there is something similar in [tcstewart/pytry](https://github.com/tcstewar/pytry). It doesn't hurt to add these few lines of code to Nengo OCL utilities, but adding pytry as a testing-only dependency might be an alternative.

Side note, pytry is in [nengo-benchmarks](https://github.com/nengo/nengo-benchmarks). Another benchmarking suite and framework - also a good one - was developed for Nengo DL. It would be great to see some kind of unification of the ideas in each benchmarking suite, but that probably has to be done on an organization basis instead of a repo basis. I'm not sure what your plans are for benchmarking Nengo Loihi. If I had a Loihi, I would want to benchmark it right away on the broadest suite of benchmarks, possibly including ones that only work on OCL and ones that only work on DL.

**Comment by hunse** [comment]
The idea behind nengo-benchmarks is to be a place for that kind of unified benchmarking suite, but we've never got around to actually bringing those different benchmarks over to it. (There's a card for it, but it's a ways down the backlog.) Part of that process would include unifying the process that we use to run the benchmarks. `pytry` definitely has some nice features, but my impression is that it currently assumes that there's not a lot of unique configuration for different backends (or what there is can all be done when creating the simulator). As we've found for the benchmarks in this repo, there can be backend-specific configuration at the network/model level, when creating the simulator, and even when calling `sim.run`. So ideally we'd have a system that can support all of that.

Are there any other features that would be helpful for comparing between different GPUs, or any of the other benchmarking you want to do?

I don't mind adding a few lines to `nengo_ocl/utils.py` to register other backends/options as we need to; based on #188, it seems pretty straight-forward. So at this point, I'm not considering checking for a separate python file to do user-specific configuration for backends.

**Comment by atait** [comment]
A benchmarking wishlist would include 1. a kernel-level profiler for OCL, like NVVP for CUDA, 2. more advanced large dataset handling, including efficient spilling RAM to disk before it overflows, and 3. multi-GPU support. I realize #3 would be very difficult, and #1 might not exist at all, but it's a wishlist ;) This PR looks good to me. I can make use of SimRunner in my user-side code with Nengo-OCL.

**Pull request merged**
